version: "3.9"

services:
  inventory-db:
    image: postgres:15
    container_name: inventory-db
    restart: always
    environment:
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory_pass
      POSTGRES_DB: inventory_db
    ports:
      - "5432:5432"
    volumes:
      - inventory_data:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  inventory-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-service
    depends_on:
      - inventory-db
    environment:
      DB_HOST: inventory-db
      DB_PORT: 5432
      DB_USER: user
      DB_PASS: 12345
      DB_NAME: inventory
    ports:
      - "3002:3002"

volumes:
  inventory_data:
