// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: inventory/v1/global/meta/meta.proto

package meta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaginationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationRequest) Reset() {
	*x = PaginationRequest{}
	mi := &file_inventory_v1_global_meta_meta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationRequest) ProtoMessage() {}

func (x *PaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_global_meta_meta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationRequest.ProtoReflect.Descriptor instead.
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_global_meta_meta_proto_rawDescGZIP(), []int{0}
}

func (x *PaginationRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *PaginationRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type FilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        string                 `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Order         string                 `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	Keyword       string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterRequest) Reset() {
	*x = FilterRequest{}
	mi := &file_inventory_v1_global_meta_meta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterRequest) ProtoMessage() {}

func (x *FilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_global_meta_meta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterRequest.ProtoReflect.Descriptor instead.
func (*FilterRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_global_meta_meta_proto_rawDescGZIP(), []int{1}
}

func (x *FilterRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *FilterRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *FilterRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type PaginationResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Offset          int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit           int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	TotalPages      int64                  `protobuf:"varint,3,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	TotalRows       int64                  `protobuf:"varint,4,opt,name=total_rows,json=totalRows,proto3" json:"total_rows,omitempty"`
	TotalRowPerPage int64                  `protobuf:"varint,5,opt,name=total_row_per_page,json=totalRowPerPage,proto3" json:"total_row_per_page,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PaginationResponse) Reset() {
	*x = PaginationResponse{}
	mi := &file_inventory_v1_global_meta_meta_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationResponse) ProtoMessage() {}

func (x *PaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_global_meta_meta_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationResponse.ProtoReflect.Descriptor instead.
func (*PaginationResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_global_meta_meta_proto_rawDescGZIP(), []int{2}
}

func (x *PaginationResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *PaginationResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PaginationResponse) GetTotalPages() int64 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *PaginationResponse) GetTotalRows() int64 {
	if x != nil {
		return x.TotalRows
	}
	return 0
}

func (x *PaginationResponse) GetTotalRowPerPage() int64 {
	if x != nil {
		return x.TotalRowPerPage
	}
	return 0
}

type Meta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int64                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	MessageCode   string                 `protobuf:"bytes,2,opt,name=message_code,json=messageCode,proto3" json:"message_code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,4,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meta) Reset() {
	*x = Meta{}
	mi := &file_inventory_v1_global_meta_meta_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_global_meta_meta_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_inventory_v1_global_meta_meta_proto_rawDescGZIP(), []int{3}
}

func (x *Meta) GetStatusCode() int64 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *Meta) GetMessageCode() string {
	if x != nil {
		return x.MessageCode
	}
	return ""
}

func (x *Meta) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Meta) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ResponseJson struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Meta                  `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Data          *anypb.Any             `protobuf:"bytes,2,opt,name=data,proto3,oneof" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseJson) Reset() {
	*x = ResponseJson{}
	mi := &file_inventory_v1_global_meta_meta_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseJson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseJson) ProtoMessage() {}

func (x *ResponseJson) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_global_meta_meta_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseJson.ProtoReflect.Descriptor instead.
func (*ResponseJson) Descriptor() ([]byte, []int) {
	return file_inventory_v1_global_meta_meta_proto_rawDescGZIP(), []int{4}
}

func (x *ResponseJson) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ResponseJson) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_inventory_v1_global_meta_meta_proto protoreflect.FileDescriptor

const file_inventory_v1_global_meta_meta_proto_rawDesc = "" +
	"\n" +
	"#inventory/v1/global/meta/meta.proto\x1a\x19google/protobuf/any.proto\"A\n" +
	"\x11PaginationRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"W\n" +
	"\rFilterRequest\x12\x16\n" +
	"\x06filter\x18\x01 \x01(\tR\x06filter\x12\x14\n" +
	"\x05order\x18\x02 \x01(\tR\x05order\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\"\xaf\x01\n" +
	"\x12PaginationResponse\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1f\n" +
	"\vtotal_pages\x18\x03 \x01(\x03R\n" +
	"totalPages\x12\x1d\n" +
	"\n" +
	"total_rows\x18\x04 \x01(\x03R\ttotalRows\x12+\n" +
	"\x12total_row_per_page\x18\x05 \x01(\x03R\x0ftotalRowPerPage\"\xad\x01\n" +
	"\x04Meta\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x03R\n" +
	"statusCode\x12!\n" +
	"\fmessage_code\x18\x02 \x01(\tR\vmessageCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x128\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x13.PaginationResponseH\x00R\n" +
	"pagination\x88\x01\x01B\r\n" +
	"\v_pagination\"a\n" +
	"\fResponseJson\x12\x19\n" +
	"\x04meta\x18\x01 \x01(\v2\x05.MetaR\x04meta\x12-\n" +
	"\x04data\x18\x02 \x01(\v2\x14.google.protobuf.AnyH\x00R\x04data\x88\x01\x01B\a\n" +
	"\x05_dataB6Z4inventory-service/protocgen/inventory/v1/global/metab\x06proto3"

var (
	file_inventory_v1_global_meta_meta_proto_rawDescOnce sync.Once
	file_inventory_v1_global_meta_meta_proto_rawDescData []byte
)

func file_inventory_v1_global_meta_meta_proto_rawDescGZIP() []byte {
	file_inventory_v1_global_meta_meta_proto_rawDescOnce.Do(func() {
		file_inventory_v1_global_meta_meta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_v1_global_meta_meta_proto_rawDesc), len(file_inventory_v1_global_meta_meta_proto_rawDesc)))
	})
	return file_inventory_v1_global_meta_meta_proto_rawDescData
}

var file_inventory_v1_global_meta_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_inventory_v1_global_meta_meta_proto_goTypes = []any{
	(*PaginationRequest)(nil),  // 0: PaginationRequest
	(*FilterRequest)(nil),      // 1: FilterRequest
	(*PaginationResponse)(nil), // 2: PaginationResponse
	(*Meta)(nil),               // 3: Meta
	(*ResponseJson)(nil),       // 4: ResponseJson
	(*anypb.Any)(nil),          // 5: google.protobuf.Any
}
var file_inventory_v1_global_meta_meta_proto_depIdxs = []int32{
	2, // 0: Meta.pagination:type_name -> PaginationResponse
	3, // 1: ResponseJson.meta:type_name -> Meta
	5, // 2: ResponseJson.data:type_name -> google.protobuf.Any
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_inventory_v1_global_meta_meta_proto_init() }
func file_inventory_v1_global_meta_meta_proto_init() {
	if File_inventory_v1_global_meta_meta_proto != nil {
		return
	}
	file_inventory_v1_global_meta_meta_proto_msgTypes[3].OneofWrappers = []any{}
	file_inventory_v1_global_meta_meta_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_v1_global_meta_meta_proto_rawDesc), len(file_inventory_v1_global_meta_meta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_inventory_v1_global_meta_meta_proto_goTypes,
		DependencyIndexes: file_inventory_v1_global_meta_meta_proto_depIdxs,
		MessageInfos:      file_inventory_v1_global_meta_meta_proto_msgTypes,
	}.Build()
	File_inventory_v1_global_meta_meta_proto = out.File
	file_inventory_v1_global_meta_meta_proto_goTypes = nil
	file_inventory_v1_global_meta_meta_proto_depIdxs = nil
}
