// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: inventory/v1/core/user/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	meta "inventory-service/protocgen/inventory/v1/global/meta"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_inventory_v1_core_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_core_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_inventory_v1_core_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *User) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_inventory_v1_core_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_core_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_core_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Meta          *meta.Meta             `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_inventory_v1_core_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_core_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_core_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *CreateUserResponse) GetMeta() *meta.Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_inventory_v1_core_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_core_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_core_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Meta          *meta.Meta             `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_inventory_v1_core_user_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_core_user_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_core_user_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetUserResponse) GetMeta() *meta.Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type ListUsersRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Pagination    *meta.PaginationRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Query         *meta.FilterRequest     `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_inventory_v1_core_user_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_core_user_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_core_user_user_proto_rawDescGZIP(), []int{5}
}

func (x *ListUsersRequest) GetPagination() *meta.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListUsersRequest) GetQuery() *meta.FilterRequest {
	if x != nil {
		return x.Query
	}
	return nil
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          []*User                `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
	Meta          *meta.Meta             `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_inventory_v1_core_user_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_core_user_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_core_user_user_proto_rawDescGZIP(), []int{6}
}

func (x *ListUsersResponse) GetUser() []*User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ListUsersResponse) GetMeta() *meta.Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_inventory_v1_core_user_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_core_user_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_core_user_user_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Meta          *meta.Meta             `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_inventory_v1_core_user_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_core_user_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_core_user_user_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UpdateUserResponse) GetMeta() *meta.Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_inventory_v1_core_user_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_core_user_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_core_user_user_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *meta.Meta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_inventory_v1_core_user_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_core_user_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_core_user_user_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteUserResponse) GetMeta() *meta.Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_inventory_v1_core_user_user_proto protoreflect.FileDescriptor

const file_inventory_v1_core_user_user_proto_rawDesc = "" +
	"\n" +
	"!inventory/v1/core/user/user.proto\x1a#inventory/v1/global/meta/meta.proto\"~\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\".\n" +
	"\x11CreateUserRequest\x12\x19\n" +
	"\x04user\x18\x01 \x01(\v2\x05.UserR\x04user\"J\n" +
	"\x12CreateUserResponse\x12\x19\n" +
	"\x04user\x18\x01 \x01(\v2\x05.UserR\x04user\x12\x19\n" +
	"\x04meta\x18\x02 \x01(\v2\x05.MetaR\x04meta\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"G\n" +
	"\x0fGetUserResponse\x12\x19\n" +
	"\x04user\x18\x01 \x01(\v2\x05.UserR\x04user\x12\x19\n" +
	"\x04meta\x18\x02 \x01(\v2\x05.MetaR\x04meta\"l\n" +
	"\x10ListUsersRequest\x122\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x12.PaginationRequestR\n" +
	"pagination\x12$\n" +
	"\x05query\x18\x02 \x01(\v2\x0e.FilterRequestR\x05query\"I\n" +
	"\x11ListUsersResponse\x12\x19\n" +
	"\x04user\x18\x01 \x03(\v2\x05.UserR\x04user\x12\x19\n" +
	"\x04meta\x18\x03 \x01(\v2\x05.MetaR\x04meta\".\n" +
	"\x11UpdateUserRequest\x12\x19\n" +
	"\x04user\x18\x01 \x01(\v2\x05.UserR\x04user\"J\n" +
	"\x12UpdateUserResponse\x12\x19\n" +
	"\x04user\x18\x01 \x01(\v2\x05.UserR\x04user\x12\x19\n" +
	"\x04meta\x18\x02 \x01(\v2\x05.MetaR\x04meta\"#\n" +
	"\x11DeleteUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"/\n" +
	"\x12DeleteUserResponse\x12\x19\n" +
	"\x04meta\x18\x01 \x01(\v2\x05.MetaR\x04meta2\x9a\x02\n" +
	"\vUserService\x125\n" +
	"\n" +
	"CreateUser\x12\x12.CreateUserRequest\x1a\x13.CreateUserResponse\x12,\n" +
	"\aGetUser\x12\x0f.GetUserRequest\x1a\x10.GetUserResponse\x122\n" +
	"\tListUsers\x12\x11.ListUsersRequest\x1a\x12.ListUsersResponse\x128\n" +
	"\rUpdateArticle\x12\x12.UpdateUserRequest\x1a\x13.UpdateUserResponse\x128\n" +
	"\rDeleteArticle\x12\x12.DeleteUserRequest\x1a\x13.DeleteUserResponseB4Z2inventory-service/protocgen/inventory/v1/core/userb\x06proto3"

var (
	file_inventory_v1_core_user_user_proto_rawDescOnce sync.Once
	file_inventory_v1_core_user_user_proto_rawDescData []byte
)

func file_inventory_v1_core_user_user_proto_rawDescGZIP() []byte {
	file_inventory_v1_core_user_user_proto_rawDescOnce.Do(func() {
		file_inventory_v1_core_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_v1_core_user_user_proto_rawDesc), len(file_inventory_v1_core_user_user_proto_rawDesc)))
	})
	return file_inventory_v1_core_user_user_proto_rawDescData
}

var file_inventory_v1_core_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_inventory_v1_core_user_user_proto_goTypes = []any{
	(*User)(nil),                   // 0: User
	(*CreateUserRequest)(nil),      // 1: CreateUserRequest
	(*CreateUserResponse)(nil),     // 2: CreateUserResponse
	(*GetUserRequest)(nil),         // 3: GetUserRequest
	(*GetUserResponse)(nil),        // 4: GetUserResponse
	(*ListUsersRequest)(nil),       // 5: ListUsersRequest
	(*ListUsersResponse)(nil),      // 6: ListUsersResponse
	(*UpdateUserRequest)(nil),      // 7: UpdateUserRequest
	(*UpdateUserResponse)(nil),     // 8: UpdateUserResponse
	(*DeleteUserRequest)(nil),      // 9: DeleteUserRequest
	(*DeleteUserResponse)(nil),     // 10: DeleteUserResponse
	(*meta.Meta)(nil),              // 11: Meta
	(*meta.PaginationRequest)(nil), // 12: PaginationRequest
	(*meta.FilterRequest)(nil),     // 13: FilterRequest
}
var file_inventory_v1_core_user_user_proto_depIdxs = []int32{
	0,  // 0: CreateUserRequest.user:type_name -> User
	0,  // 1: CreateUserResponse.user:type_name -> User
	11, // 2: CreateUserResponse.meta:type_name -> Meta
	0,  // 3: GetUserResponse.user:type_name -> User
	11, // 4: GetUserResponse.meta:type_name -> Meta
	12, // 5: ListUsersRequest.pagination:type_name -> PaginationRequest
	13, // 6: ListUsersRequest.query:type_name -> FilterRequest
	0,  // 7: ListUsersResponse.user:type_name -> User
	11, // 8: ListUsersResponse.meta:type_name -> Meta
	0,  // 9: UpdateUserRequest.user:type_name -> User
	0,  // 10: UpdateUserResponse.user:type_name -> User
	11, // 11: UpdateUserResponse.meta:type_name -> Meta
	11, // 12: DeleteUserResponse.meta:type_name -> Meta
	1,  // 13: UserService.CreateUser:input_type -> CreateUserRequest
	3,  // 14: UserService.GetUser:input_type -> GetUserRequest
	5,  // 15: UserService.ListUsers:input_type -> ListUsersRequest
	7,  // 16: UserService.UpdateArticle:input_type -> UpdateUserRequest
	9,  // 17: UserService.DeleteArticle:input_type -> DeleteUserRequest
	2,  // 18: UserService.CreateUser:output_type -> CreateUserResponse
	4,  // 19: UserService.GetUser:output_type -> GetUserResponse
	6,  // 20: UserService.ListUsers:output_type -> ListUsersResponse
	8,  // 21: UserService.UpdateArticle:output_type -> UpdateUserResponse
	10, // 22: UserService.DeleteArticle:output_type -> DeleteUserResponse
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_inventory_v1_core_user_user_proto_init() }
func file_inventory_v1_core_user_user_proto_init() {
	if File_inventory_v1_core_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_v1_core_user_user_proto_rawDesc), len(file_inventory_v1_core_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_v1_core_user_user_proto_goTypes,
		DependencyIndexes: file_inventory_v1_core_user_user_proto_depIdxs,
		MessageInfos:      file_inventory_v1_core_user_user_proto_msgTypes,
	}.Build()
	File_inventory_v1_core_user_user_proto = out.File
	file_inventory_v1_core_user_user_proto_goTypes = nil
	file_inventory_v1_core_user_user_proto_depIdxs = nil
}
