// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: inventory/v1/core/orders/orders.proto

package orders

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	meta "inventory-service/protocgen/inventory/v1/global/meta"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     int32                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	UserId        int32                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // CREATED, CONFIRMED, CANCELED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_inventory_v1_core_orders_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_core_orders_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_inventory_v1_core_orders_orders_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *Order) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UserId        int32                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_inventory_v1_core_orders_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_core_orders_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_core_orders_orders_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateOrderRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateOrderRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Meta          *meta.Meta             `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_inventory_v1_core_orders_orders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_core_orders_orders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_core_orders_orders_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *CreateOrderResponse) GetMeta() *meta.Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_inventory_v1_core_orders_orders_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_core_orders_orders_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_core_orders_orders_proto_rawDescGZIP(), []int{3}
}

func (x *CancelOrderRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *meta.Meta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_inventory_v1_core_orders_orders_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_core_orders_orders_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_core_orders_orders_proto_rawDescGZIP(), []int{4}
}

func (x *CancelOrderResponse) GetMeta() *meta.Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_inventory_v1_core_orders_orders_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_core_orders_orders_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_core_orders_orders_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrderRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type GetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Meta          *meta.Meta             `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_inventory_v1_core_orders_orders_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_core_orders_orders_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_core_orders_orders_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *GetOrderResponse) GetMeta() *meta.Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_inventory_v1_core_orders_orders_proto protoreflect.FileDescriptor

const file_inventory_v1_core_orders_orders_proto_rawDesc = "" +
	"\n" +
	"%inventory/v1/core/orders/orders.proto\x1a#inventory/v1/global/meta/meta.proto\"g\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x05R\tproductId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x05R\x06userId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"h\n" +
	"\x12CreateOrderRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x05R\x06userId\"N\n" +
	"\x13CreateOrderResponse\x12\x1c\n" +
	"\x05order\x18\x01 \x01(\v2\x06.OrderR\x05order\x12\x19\n" +
	"\x04meta\x18\x02 \x01(\v2\x05.MetaR\x04meta\"/\n" +
	"\x12CancelOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x05R\aorderId\"0\n" +
	"\x13CancelOrderResponse\x12\x19\n" +
	"\x04meta\x18\x01 \x01(\v2\x05.MetaR\x04meta\",\n" +
	"\x0fGetOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x05R\aorderId\"K\n" +
	"\x10GetOrderResponse\x12\x1c\n" +
	"\x05order\x18\x01 \x01(\v2\x06.OrderR\x05order\x12\x19\n" +
	"\x04meta\x18\x02 \x01(\v2\x05.MetaR\x04meta2\xb3\x01\n" +
	"\fOrderService\x128\n" +
	"\vCreateOrder\x12\x13.CreateOrderRequest\x1a\x14.CreateOrderResponse\x128\n" +
	"\vCancelOrder\x12\x13.CancelOrderRequest\x1a\x14.CancelOrderResponse\x12/\n" +
	"\bGetOrder\x12\x10.GetOrderRequest\x1a\x11.GetOrderResponseB6Z4inventory-service/protocgen/inventory/v1/core/ordersb\x06proto3"

var (
	file_inventory_v1_core_orders_orders_proto_rawDescOnce sync.Once
	file_inventory_v1_core_orders_orders_proto_rawDescData []byte
)

func file_inventory_v1_core_orders_orders_proto_rawDescGZIP() []byte {
	file_inventory_v1_core_orders_orders_proto_rawDescOnce.Do(func() {
		file_inventory_v1_core_orders_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_v1_core_orders_orders_proto_rawDesc), len(file_inventory_v1_core_orders_orders_proto_rawDesc)))
	})
	return file_inventory_v1_core_orders_orders_proto_rawDescData
}

var file_inventory_v1_core_orders_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_inventory_v1_core_orders_orders_proto_goTypes = []any{
	(*Order)(nil),               // 0: Order
	(*CreateOrderRequest)(nil),  // 1: CreateOrderRequest
	(*CreateOrderResponse)(nil), // 2: CreateOrderResponse
	(*CancelOrderRequest)(nil),  // 3: CancelOrderRequest
	(*CancelOrderResponse)(nil), // 4: CancelOrderResponse
	(*GetOrderRequest)(nil),     // 5: GetOrderRequest
	(*GetOrderResponse)(nil),    // 6: GetOrderResponse
	(*meta.Meta)(nil),           // 7: Meta
}
var file_inventory_v1_core_orders_orders_proto_depIdxs = []int32{
	0, // 0: CreateOrderResponse.order:type_name -> Order
	7, // 1: CreateOrderResponse.meta:type_name -> Meta
	7, // 2: CancelOrderResponse.meta:type_name -> Meta
	0, // 3: GetOrderResponse.order:type_name -> Order
	7, // 4: GetOrderResponse.meta:type_name -> Meta
	1, // 5: OrderService.CreateOrder:input_type -> CreateOrderRequest
	3, // 6: OrderService.CancelOrder:input_type -> CancelOrderRequest
	5, // 7: OrderService.GetOrder:input_type -> GetOrderRequest
	2, // 8: OrderService.CreateOrder:output_type -> CreateOrderResponse
	4, // 9: OrderService.CancelOrder:output_type -> CancelOrderResponse
	6, // 10: OrderService.GetOrder:output_type -> GetOrderResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_inventory_v1_core_orders_orders_proto_init() }
func file_inventory_v1_core_orders_orders_proto_init() {
	if File_inventory_v1_core_orders_orders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_v1_core_orders_orders_proto_rawDesc), len(file_inventory_v1_core_orders_orders_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_v1_core_orders_orders_proto_goTypes,
		DependencyIndexes: file_inventory_v1_core_orders_orders_proto_depIdxs,
		MessageInfos:      file_inventory_v1_core_orders_orders_proto_msgTypes,
	}.Build()
	File_inventory_v1_core_orders_orders_proto = out.File
	file_inventory_v1_core_orders_orders_proto_goTypes = nil
	file_inventory_v1_core_orders_orders_proto_depIdxs = nil
}
