// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: inventory/v1/core/products/products.proto

package products

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	meta "inventory-service/protocgen/inventory/v1/global/meta"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Products struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Tag           []string               `protobuf:"bytes,5,rep,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Products) Reset() {
	*x = Products{}
	mi := &file_inventory_v1_core_products_products_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Products) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Products) ProtoMessage() {}

func (x *Products) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_core_products_products_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Products.ProtoReflect.Descriptor instead.
func (*Products) Descriptor() ([]byte, []int) {
	return file_inventory_v1_core_products_products_proto_rawDescGZIP(), []int{0}
}

func (x *Products) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Products) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Products) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Products) GetTag() []string {
	if x != nil {
		return x.Tag
	}
	return nil
}

type CreateProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      *Products              `protobuf:"bytes,1,opt,name=Products,proto3" json:"Products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductsRequest) Reset() {
	*x = CreateProductsRequest{}
	mi := &file_inventory_v1_core_products_products_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductsRequest) ProtoMessage() {}

func (x *CreateProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_core_products_products_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductsRequest.ProtoReflect.Descriptor instead.
func (*CreateProductsRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_core_products_products_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductsRequest) GetProducts() *Products {
	if x != nil {
		return x.Products
	}
	return nil
}

type CreateProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      *Products              `protobuf:"bytes,1,opt,name=Products,proto3" json:"Products,omitempty"`
	Meta          *meta.Meta             `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductsResponse) Reset() {
	*x = CreateProductsResponse{}
	mi := &file_inventory_v1_core_products_products_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductsResponse) ProtoMessage() {}

func (x *CreateProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_core_products_products_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductsResponse.ProtoReflect.Descriptor instead.
func (*CreateProductsResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_core_products_products_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProductsResponse) GetProducts() *Products {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *CreateProductsResponse) GetMeta() *meta.Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsRequest) Reset() {
	*x = GetProductsRequest{}
	mi := &file_inventory_v1_core_products_products_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsRequest) ProtoMessage() {}

func (x *GetProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_core_products_products_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsRequest.ProtoReflect.Descriptor instead.
func (*GetProductsRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_core_products_products_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductsRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      *Products              `protobuf:"bytes,1,opt,name=Products,proto3" json:"Products,omitempty"`
	Meta          *meta.Meta             `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsResponse) Reset() {
	*x = GetProductsResponse{}
	mi := &file_inventory_v1_core_products_products_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsResponse) ProtoMessage() {}

func (x *GetProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_core_products_products_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsResponse.ProtoReflect.Descriptor instead.
func (*GetProductsResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_core_products_products_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductsResponse) GetProducts() *Products {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *GetProductsResponse) GetMeta() *meta.Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type ListProductssRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Pagination    *meta.PaginationRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Query         *meta.FilterRequest     `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductssRequest) Reset() {
	*x = ListProductssRequest{}
	mi := &file_inventory_v1_core_products_products_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductssRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductssRequest) ProtoMessage() {}

func (x *ListProductssRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_core_products_products_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductssRequest.ProtoReflect.Descriptor instead.
func (*ListProductssRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_core_products_products_proto_rawDescGZIP(), []int{5}
}

func (x *ListProductssRequest) GetPagination() *meta.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListProductssRequest) GetQuery() *meta.FilterRequest {
	if x != nil {
		return x.Query
	}
	return nil
}

type ListProductssResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Productss     []*Products            `protobuf:"bytes,1,rep,name=Productss,proto3" json:"Productss,omitempty"`
	Meta          *meta.Meta             `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductssResponse) Reset() {
	*x = ListProductssResponse{}
	mi := &file_inventory_v1_core_products_products_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductssResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductssResponse) ProtoMessage() {}

func (x *ListProductssResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_core_products_products_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductssResponse.ProtoReflect.Descriptor instead.
func (*ListProductssResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_core_products_products_proto_rawDescGZIP(), []int{6}
}

func (x *ListProductssResponse) GetProductss() []*Products {
	if x != nil {
		return x.Productss
	}
	return nil
}

func (x *ListProductssResponse) GetMeta() *meta.Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type UpdateProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      *Products              `protobuf:"bytes,1,opt,name=Products,proto3" json:"Products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductsRequest) Reset() {
	*x = UpdateProductsRequest{}
	mi := &file_inventory_v1_core_products_products_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductsRequest) ProtoMessage() {}

func (x *UpdateProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_core_products_products_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductsRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductsRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_core_products_products_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateProductsRequest) GetProducts() *Products {
	if x != nil {
		return x.Products
	}
	return nil
}

type UpdateProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      *Products              `protobuf:"bytes,1,opt,name=Products,proto3" json:"Products,omitempty"`
	Meta          *meta.Meta             `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductsResponse) Reset() {
	*x = UpdateProductsResponse{}
	mi := &file_inventory_v1_core_products_products_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductsResponse) ProtoMessage() {}

func (x *UpdateProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_core_products_products_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductsResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductsResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_core_products_products_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateProductsResponse) GetProducts() *Products {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *UpdateProductsResponse) GetMeta() *meta.Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type DeleteProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductsRequest) Reset() {
	*x = DeleteProductsRequest{}
	mi := &file_inventory_v1_core_products_products_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductsRequest) ProtoMessage() {}

func (x *DeleteProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_core_products_products_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductsRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductsRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_core_products_products_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteProductsRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      *Products              `protobuf:"bytes,1,opt,name=Products,proto3" json:"Products,omitempty"`
	Meta          *meta.Meta             `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductsResponse) Reset() {
	*x = DeleteProductsResponse{}
	mi := &file_inventory_v1_core_products_products_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductsResponse) ProtoMessage() {}

func (x *DeleteProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_core_products_products_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductsResponse.ProtoReflect.Descriptor instead.
func (*DeleteProductsResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_core_products_products_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteProductsResponse) GetProducts() *Products {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *DeleteProductsResponse) GetMeta() *meta.Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_inventory_v1_core_products_products_proto protoreflect.FileDescriptor

const file_inventory_v1_core_products_products_proto_rawDesc = "" +
	"\n" +
	")inventory/v1/core/products/products.proto\x1a#inventory/v1/global/meta/meta.proto\"\\\n" +
	"\bProducts\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x10\n" +
	"\x03tag\x18\x05 \x03(\tR\x03tag\">\n" +
	"\x15CreateProductsRequest\x12%\n" +
	"\bProducts\x18\x01 \x01(\v2\t.ProductsR\bProducts\"Z\n" +
	"\x16CreateProductsResponse\x12%\n" +
	"\bProducts\x18\x01 \x01(\v2\t.ProductsR\bProducts\x12\x19\n" +
	"\x04meta\x18\x02 \x01(\v2\x05.MetaR\x04meta\"$\n" +
	"\x12GetProductsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"W\n" +
	"\x13GetProductsResponse\x12%\n" +
	"\bProducts\x18\x01 \x01(\v2\t.ProductsR\bProducts\x12\x19\n" +
	"\x04meta\x18\x02 \x01(\v2\x05.MetaR\x04meta\"p\n" +
	"\x14ListProductssRequest\x122\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x12.PaginationRequestR\n" +
	"pagination\x12$\n" +
	"\x05query\x18\x02 \x01(\v2\x0e.FilterRequestR\x05query\"[\n" +
	"\x15ListProductssResponse\x12'\n" +
	"\tProductss\x18\x01 \x03(\v2\t.ProductsR\tProductss\x12\x19\n" +
	"\x04meta\x18\x03 \x01(\v2\x05.MetaR\x04meta\">\n" +
	"\x15UpdateProductsRequest\x12%\n" +
	"\bProducts\x18\x01 \x01(\v2\t.ProductsR\bProducts\"Z\n" +
	"\x16UpdateProductsResponse\x12%\n" +
	"\bProducts\x18\x01 \x01(\v2\t.ProductsR\bProducts\x12\x19\n" +
	"\x04meta\x18\x02 \x01(\v2\x05.MetaR\x04meta\"'\n" +
	"\x15DeleteProductsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"Z\n" +
	"\x16DeleteProductsResponse\x12%\n" +
	"\bProducts\x18\x01 \x01(\v2\t.ProductsR\bProducts\x12\x19\n" +
	"\x04meta\x18\x02 \x01(\v2\x05.MetaR\x04meta2\xd4\x02\n" +
	"\x0fProductsService\x12A\n" +
	"\x0eCreateProducts\x12\x16.CreateProductsRequest\x1a\x17.CreateProductsResponse\x128\n" +
	"\vGetProducts\x12\x13.GetProductsRequest\x1a\x14.GetProductsResponse\x12>\n" +
	"\rListProductss\x12\x15.ListProductssRequest\x1a\x16.ListProductssResponse\x12A\n" +
	"\x0eUpdateProducts\x12\x16.UpdateProductsRequest\x1a\x17.UpdateProductsResponse\x12A\n" +
	"\x0eDeleteProducts\x12\x16.DeleteProductsRequest\x1a\x17.DeleteProductsResponseB8Z6inventory-service/protocgen/inventory/v1/core/productsb\x06proto3"

var (
	file_inventory_v1_core_products_products_proto_rawDescOnce sync.Once
	file_inventory_v1_core_products_products_proto_rawDescData []byte
)

func file_inventory_v1_core_products_products_proto_rawDescGZIP() []byte {
	file_inventory_v1_core_products_products_proto_rawDescOnce.Do(func() {
		file_inventory_v1_core_products_products_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_v1_core_products_products_proto_rawDesc), len(file_inventory_v1_core_products_products_proto_rawDesc)))
	})
	return file_inventory_v1_core_products_products_proto_rawDescData
}

var file_inventory_v1_core_products_products_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_inventory_v1_core_products_products_proto_goTypes = []any{
	(*Products)(nil),               // 0: Products
	(*CreateProductsRequest)(nil),  // 1: CreateProductsRequest
	(*CreateProductsResponse)(nil), // 2: CreateProductsResponse
	(*GetProductsRequest)(nil),     // 3: GetProductsRequest
	(*GetProductsResponse)(nil),    // 4: GetProductsResponse
	(*ListProductssRequest)(nil),   // 5: ListProductssRequest
	(*ListProductssResponse)(nil),  // 6: ListProductssResponse
	(*UpdateProductsRequest)(nil),  // 7: UpdateProductsRequest
	(*UpdateProductsResponse)(nil), // 8: UpdateProductsResponse
	(*DeleteProductsRequest)(nil),  // 9: DeleteProductsRequest
	(*DeleteProductsResponse)(nil), // 10: DeleteProductsResponse
	(*meta.Meta)(nil),              // 11: Meta
	(*meta.PaginationRequest)(nil), // 12: PaginationRequest
	(*meta.FilterRequest)(nil),     // 13: FilterRequest
}
var file_inventory_v1_core_products_products_proto_depIdxs = []int32{
	0,  // 0: CreateProductsRequest.Products:type_name -> Products
	0,  // 1: CreateProductsResponse.Products:type_name -> Products
	11, // 2: CreateProductsResponse.meta:type_name -> Meta
	0,  // 3: GetProductsResponse.Products:type_name -> Products
	11, // 4: GetProductsResponse.meta:type_name -> Meta
	12, // 5: ListProductssRequest.pagination:type_name -> PaginationRequest
	13, // 6: ListProductssRequest.query:type_name -> FilterRequest
	0,  // 7: ListProductssResponse.Productss:type_name -> Products
	11, // 8: ListProductssResponse.meta:type_name -> Meta
	0,  // 9: UpdateProductsRequest.Products:type_name -> Products
	0,  // 10: UpdateProductsResponse.Products:type_name -> Products
	11, // 11: UpdateProductsResponse.meta:type_name -> Meta
	0,  // 12: DeleteProductsResponse.Products:type_name -> Products
	11, // 13: DeleteProductsResponse.meta:type_name -> Meta
	1,  // 14: ProductsService.CreateProducts:input_type -> CreateProductsRequest
	3,  // 15: ProductsService.GetProducts:input_type -> GetProductsRequest
	5,  // 16: ProductsService.ListProductss:input_type -> ListProductssRequest
	7,  // 17: ProductsService.UpdateProducts:input_type -> UpdateProductsRequest
	9,  // 18: ProductsService.DeleteProducts:input_type -> DeleteProductsRequest
	2,  // 19: ProductsService.CreateProducts:output_type -> CreateProductsResponse
	4,  // 20: ProductsService.GetProducts:output_type -> GetProductsResponse
	6,  // 21: ProductsService.ListProductss:output_type -> ListProductssResponse
	8,  // 22: ProductsService.UpdateProducts:output_type -> UpdateProductsResponse
	10, // 23: ProductsService.DeleteProducts:output_type -> DeleteProductsResponse
	19, // [19:24] is the sub-list for method output_type
	14, // [14:19] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_inventory_v1_core_products_products_proto_init() }
func file_inventory_v1_core_products_products_proto_init() {
	if File_inventory_v1_core_products_products_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_v1_core_products_products_proto_rawDesc), len(file_inventory_v1_core_products_products_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_v1_core_products_products_proto_goTypes,
		DependencyIndexes: file_inventory_v1_core_products_products_proto_depIdxs,
		MessageInfos:      file_inventory_v1_core_products_products_proto_msgTypes,
	}.Build()
	File_inventory_v1_core_products_products_proto = out.File
	file_inventory_v1_core_products_products_proto_goTypes = nil
	file_inventory_v1_core_products_products_proto_depIdxs = nil
}
